# Generated by Django 3.2.8 on 2021-11-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='roomId',
            field=models.IntegerField(default=0),
        ),
    ]
